version: "3.8"
services:
  web:
    container_name: portopad_web
    build:
      context: .
      args:
        APP_NAME: ${APP_NAME}
    ports:
      - "${PORT}:80"
    environment:
      - NGINX_HOST=${NGINX_HOST}
    volumes:
      - ./src:/app/src
    restart: always
