name: "Update Angular Action"
on:
  schedule:
    - cron: "30 5 * * 3"

jobs:
  ngxUptodate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Updating ng dependencies
        uses: fast-facts/ng-update@v1.0.0
        with:
          base-branch: main
          repo-token: ${{ secrets.GITHUB_TOKEN }}
